### ISSUE TITLE
Hadoop 2.0+ Support

### ISSUE THREAD

**Issue by tarnfeld** [cemeyer/hadoofus#19]
Just opening this issue for brainstorming, it'd be really nice to support Hadoop 2.

It's worth noting that HDFS now uses protocol buffer objects – [see here for version 2.3.0](https://github.com/apache/hadoop-common/blob/b8c7b6d4527743e7424d3e8f620639d272bec250/hadoop-hdfs-project/hadoop-hdfs/src/main/proto/hdfs.proto).

**Comment by cemeyer** [comment]
TODO:
* Add new exception types
* Implement v2+ datanode communication

I'm punting on the rest of the RPCs to issue #29.

**Comment by tarnfeld** [comment]
![](http://www.reactiongifs.com/r/titg.gif)
