### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by hainguyenhn** [cemeyer/hadoofus#34]
I'm trying to build py wrapper.
my-Mac:py hai$ cc -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes gcc -arch x86_64 -arch i386 -pipe -fPIC -g -fvisibility=hidden -DNO_EXPORT_SYMS -std=gnu99 -I/Users/hai/Documents/hadoofus-master/include -I/usr/local/include -c /Users/hai/Documents/hadoofus-master/src/datanode.c -o build/temp.macosx-10.10-intel-2.7/Users/hai/Documents/hadoofus-master/src/datanode.o
clang: error: no such file or directory: 'gcc'

then I try
my-Mac:py hai$ cc -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes  -arch x86_64 -arch i386 -pipe -fPIC -g -fvisibility=hidden -DNO_EXPORT_SYMS -std=gnu99 -I/Users/hai/Documents/hadoofus-master/include -I/usr/local/include -c /Users/hai/Documents/hadoofus-master/src/datanode.c -o build/temp.macosx-10.10-intel-2.7/Users/hai/Documents/hadoofus-master/src/datanode.o
In file included from /Users/hai/Documents/hadoofus-master/src/datanode.c:17:
/Users/hai/Documents/hadoofus-master/src/objects-internal.h:8:10: fatal error: 
      'hdfs.pb-c.h' file not found
#include "hdfs.pb-c.h"

I"m a noob so please help :D

**Comment by cemeyer** [comment]
Not sure how you arrived at those particular 'cc' lines.

You need `protobuf-c` and `cython` installed, then from the root directory run `gmake all`.
