### ISSUE TITLE
Two hang conditions

### ISSUE THREAD

**Issue by AndreyNevolin** [cemeyer/hadoofus#35]
Hi,

You might be interested in a couple of hang conditions I detected when I used the library recently. I haven't investigated them in details. But maybe the backtraces below will give you a general idea. Also I can try to collect more information if you need it.

1) The condition I see very often is the following (pictures below show 2 threads and backtraces for each of them)

![2-1](https://cloud.githubusercontent.com/assets/7734325/16270738/04277e86-38a0-11e6-85fc-49679bac7bfc.png)

![2-2](https://cloud.githubusercontent.com/assets/7734325/16270742/09b3f596-38a0-11e6-9244-3d51d7ada86f.png)

![2-3](https://cloud.githubusercontent.com/assets/7734325/16270747/0dcb9e04-38a0-11e6-89e1-1cda8569251a.png)

I guess, the condition occurs when some worker thread dies on the server side, the socket buffer on the server side becomes full, and Hadoofus hangs waiting for blocking write operation. But this is just a hypothesis. I haven't dove into Hadoofus code. Also I cannot investigate the condition on the server side, because I don't have sufficient knowledge of the platform. But together we could figure out the way to investigate the condition.

2) The second condition is quite rare. And information about it is very poor (only one thread is alive, and it waits for something from - presumably - already completed threads).

![1](https://cloud.githubusercontent.com/assets/7734325/16271120/621348c6-38a1-11e6-80d6-df929e793100.png)

I'm using the 'head' of 'master' branch (with most recent commits done on May 16).

**Comment by cemeyer** [comment]
Interesting, thanks.

(1) does look like the server has stopped accepting more data, but hasn't closed the socket.  I think waiting is the right thing for the client to do in this case.  Maybe the server has a bug, if it gets stuck like this and never proceeds.

(2) Is your program racily destroying the `hdfs_namenode` object and performing an `hdfs_complete` RPC in another thread?  It looks like the `_namenode_recv_worker` thread has exited, which suggests the `hdfs_namenode` object is being destroyed.

Probably the receive worker thread exits sooner than it should — it should only exit when `nn_refs` is exactly 1.  But this can be worked around in applications by draining RPCs before destroying the connection.  If you have an easy way to reproduce (2), that would be awesome.

**Comment by AndreyNevolin** [comment]
Thanks for your interest.

(1) 

>  I think waiting is the right thing for the client to do in this case

Ok, thanks. I just wanted to make sure that it's intentional behavior. I'll contact you by e-mail. Maybe you could have an idea how to find out what's wrong with the server.

(2) 

> Is your program racily destroying the  `hdfs_namenode  `object and performing an ` hdfs_complete  `?


No. It was detected on single-thread test. There was no concurrency at all (at least at the user-program level).

I'll try to reproduce and check suggested variable, but the condition is quite rare.

Anyway, the idea to return an error when problems with connection are detected sounds very reasonable.

**Comment by cemeyer** [comment]
Andrey, I have a proposed patch in https://github.com/cemeyer/hadoofus/compare/for-35 .  It compiles but I am unable to test it very soon.  If you would like to test it and/or review it, I would appreciate that.

**Comment by AndreyNevolin** [comment]
I'll test it.
